import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const helveticaRegular = localFont({
  src: './fonts/helvetica_regular.otf',
  variable: '--font-helvetica-regular',
});
const helveticaNeueRegular = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-helveticaNeue-regular',
  weight: '100 900',
});
const interTight = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-interTight',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${helveticaRegular.variable} ${helveticaNeueRegular.variable} ${interTight.variable} antialiased mx-[20%] my-[5%]`}
      >
        {children}
      </body>
    </html>
  );
}
